---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "comment.fullname" . }}
  labels:
    app: reddit
    component: comment
    release: {{ .Release.Name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: comment
      release: {{ .Release.Name }}
  template:
    metadata:
      name: comment
      labels:
        app: reddit
        component: comment
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}/ui:{{ .Values.image.tag }}‚Äù
        name: comment
        ports:
          - containerPort: {{ .Values.service.internalPort }}
            name: comment
            protocol: TCP
        env:
          - name: COMMENT_DATABASE_HOST
            value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}

